# Sunitinib simulation - checking models are coding correctly by comparing plots
# generated by simulations with published figures
# ------------------------------------------------------------------------------
# Population characteristics
# Number of individuals to simulate
  nid <- 100
  nsim <- 10
  ntotal <- nid*nsim
  SIM.seq <- rep(1:nsim,times = nid) %>% sort
  ID.seq <- rep(1:nid,times = nsim)

# Covariates
# Weight (kg)
  WT <- rlnorm(nid,meanlog = log(82.3),sd = 0.2)
  WT[WT < 39] <- 39
  WT[WT > 157] <- 157
# Baseline tumour size
  first.OBASE <- exp(log(rnorm(nid,mean = 195,sd = 120)))
  repeat {
    new.OBASE <- first.OBASE[first.OBASE == "NaN"]
    new.OBASE <- exp(log(rnorm(length(new.OBASE),mean = 195,sd = 120)))
    if (length(new.OBASE[new.OBASE == "NaN"]) == 0) break
  }
  OBASE <- c(first.OBASE[first.OBASE != "NaN"],new.OBASE)
  # plot(hist(OBASE))
# Baseline hand-foot syndrome grade
  hfs.grade0.prob <- 0.95
  hfs.grade1.prob <- 0.02
  hfs.grade2.prob <- 0.02
  hfs.grade3.prob <- 0.01
  base.hfs.probs <- c(hfs.grade0.prob,hfs.grade1.prob,hfs.grade2.prob,
    hfs.grade3.prob)
  HFSBASE <- unlist(llply(seq_len(ntotal),
    function(x) sample(c(0,1,2,3),size = x/x,prob = base.hfs.probs)))
# Baseline fatigue grade
  fat.grade0.prob <- 0.85
  fat.grade1.prob <- 0.09
  fat.grade2.prob <- 0.05
  fat.grade3.prob <- 0.01
  base.fat.probs <- c(fat.grade0.prob,fat.grade1.prob,fat.grade2.prob,
    fat.grade3.prob)
  FATBASE <- unlist(llply(seq_len(ntotal),
    function(x) sample(c(0,1,2,3),size = x/x,prob = base.fat.probs)))

# ------------------------------------------------------------------------------
# Time sequences
  nweeks <- 50
# Pharmacokinetics
# Simulation times (hours)
  end.pk.time <- nweeks*24*7	# end simulation time
  pk.increment <- 24 # concentration collection times
  pk.times <- seq(from = 0,to = end.pk.time,by = pk.increment) # hours

  # # Specify cycle times
  #   cycle25 <- seq(from = 0,to = 6*7*24-1,by = pk.increment)
  #   cycle375 <- seq(from = 6*7*24,to = 12*7*24-1,by = pk.increment)
  #   cycle50 <- seq(from = 12*7*24,to = 18*7*24-1,by = pk.increment)
  #   cycle75 <- seq(from = 18*7*24,to = 24*7*24-1,by = pk.increment)

# Pharmacodynamics
  end.pd.time <- nweeks*24*7	# end simulation time
  pd.increment <- 6*24*7	# measurement times
  pd.times <- seq(from = 0,to = end.pd.time,by = pd.increment)

# Time to event/overall survival
  end.surv.time <- nweeks	# end simulation time (200 weeks)
  surv.increment <- 2	# measurement times
  surv.times <- seq(from = 0,to = end.surv.time,by = surv.increment)

# ------------------------------------------------------------------------------
# Dosing specifications
  # dose <- 37.5	# mg, continuous dosing
  # on.times <- seq(from = 0,to = max(end.pk.time),by = 24)

  dose <- 50	# mg
  cycles <- 1:50	# number of cycles
  cycle.duration <- 6	# weeks
  on.times <- seq(from = 0,to = 4*7*24-24,by = 24)	# 4 weeks in hours
  add.times <- llply(seq_len(max(cycles)),function(x) {
    add.times <- cycles[x]*cycle.duration*7*24+
    seq(from = 0,to = 4*7*24-24,by = 24)
  })
  add.times <- unlist(add.times)
  on.times <- c(on.times,add.times)
