# Sunitinib simulation - checking models are coding correctly by comparing plots
# generated by simulations with published figures
# ------------------------------------------------------------------------------
# Remove objects in workspace
  rm(list = ls(all = TRUE))
# Define global directory for project
  global.dir <- "/Volumes/Prosecutor/sunitinib/Project/"
# Source required files
  source(paste0(global.dir,"functions.R"))	# Universal functions file
  source(paste0(global.dir,"ModelFiles/yu_2015_sunitinib_model.R"))	# PopPK model
  source(paste0(global.dir,"ModelFiles/hansson_2013_sunitinib_models.R"))	# PD models
# Define simulation file directory
  sim.dir <- paste0(global.dir,"SimulationFiles/")
  source(paste0(sim.dir,"test_sunitinib_simulation_options.R"))	# Simulation options file
# Define output directory
  output.dir <- paste0(global.dir,"Output/TestSimulation/")
# Set the working directory
  setwd(output.dir)

# ------------------------------------------------------------------------------
# Generate random effect parameters
# Between subject variability
  if (ntotal > 1) {
    pk.ETA.matrix <- mvrnorm(ntotal,
      mu = rep(0,times = dim(pk.OMEGA)[1]),pk.OMEGA) %>%
      as.data.frame
    names(pk.ETA.matrix) <- c("ETACLP","ETAVCP","ETACLM","ETAVCM")

    pd.ETA.matrix <- mvrnorm(ntotal,
      mu = rep(0,times = dim(pd.OMEGA)[1]),pd.OMEGA) %>%
      as.data.frame
    names(pd.ETA.matrix) <- c("ETAVEGFR3BASE","ETAVEGFR3MRT","ETAVEGFR3I50",
      "ETASKITBASE","ETASKITMRT","ETASKITI50","ETASKITSLP","ETAKG","ETAKRSKIT",
      "ETAKRD","ETAOBASE","ETAANCBASE","ETAANCMTT","ETAANCEMAX","ETAANCE50",
      "ETABPBASE","ETABPSLP","ETABPMRT","ETAHFS0","ETAHFS1","ETAHFS2","ETAFAT0",
      "ETAFAT1","ETAFAT2","ETAFAT3")
  } else {
    pk.ETA.matrix <- data.frame(ETACLP = 0,ETAVCP = 0,ETACLM = 0,ETAVCM = 0)
    pd.ETA.matrix <- data.frame(ETAVEGFR3BASE = 0,ETAVEGFR3MRT = 0,
      ETASKITBASE = 0,ETASKITMRT = 0,ETASKITSLP = 0,ETAVEGFR3I50 = 0,
      ETASKITI50 = 0,ETAKG = 0,ETAKRSKIT = 0,ETAKRD = 0,ETAOBASE = 0,
      ETAANCBASE = 0,ETAANCMTT = 0,ETAANCEMAX = 0,ETAANCE50 = 0,ETABPBASE = 0,
      ETABPSLP = 0,ETABPMRT = 0,ETAHFS0 = 0,ETAHFS1 = 0,ETAHFS2 = 0,ETAFAT0 = 0,
      ETAFAT1 = 0,ETAFAT2 = 0,ETAFAT3 = 0)
  }

# ------------------------------------------------------------------------------
# Perform PK simulations
# Input data frame for simulation
  pk.ID.data <- data.frame(SIM = SIM.seq,ID = ID.seq,WT,OBASE,HFSBASE,FATBASE,
    pk.ETA.matrix)
  input.pk.data <- lapply(pk.ID.data,rep.int,times = length(pk.times)) %>%
    as.data.frame
  input.pk.data <- input.pk.data[with(input.pk.data,
    order(input.pk.data$SIM,input.pk.data$ID)),]
  input.pk.data$time <- pk.times
  input.pk.data$cmt <- 1
  # input.pk.data$amt[input.pk.data$time %in% cycle25] <- 25	# First cycle
  # input.pk.data$amt[input.pk.data$time %in% cycle375] <- 37.5	# Second cycle
  # input.pk.data$amt[input.pk.data$time %in% cycle50] <- 50	# Third cycle
  # input.pk.data$amt[input.pk.data$time %in% cycle75] <- 75	# Fourth cycle
  input.pk.data$amt <- dose
  input.pk.data$evid <- 0
  input.pk.data$evid[input.pk.data$time %in% on.times] <- 1

# Simulate
  pk.data <- pk.mod %>% mrgsim(data = input.pk.data,
    carry.out = c("SIM","amt")) %>%
    as.data.frame
# Calculate 24-hour AUCs (of the combined parent and metabolite)
  pk.data <- ddply(pk.data, .(SIM,ID), auc24.function, .progress = "text")

# # Summarise data as median and confidence intervals
#   pk.time.data <- pk.data[pk.data$time <= 12*24*7,]	# Subset times less than 12 weeks
#   summary.IPREP <- ddply(pk.time.data, .(time),
#     function(pk.time.data) summary.function(pk.time.data$IPREP))
#   summary.IPREM <- ddply(pk.time.data, .(time),
#     function(pk.time.data) summary.function(pk.time.data$IPREM))
#   summary.IPRE <- ddply(pk.time.data, .(time),
#     function(pk.time.data) summary.function(pk.time.data$IPRE))
#   summary.AUC24 <- ddply(pk.time.data, .(time),
#     function(pk.time.data) summary.function(pk.time.data$AUC24))
#
# # Plot parent, metabolite and combined sunitinib concentrations over time
#   plotobj1 <- NULL
#   plotobj1 <- ggplot()
#   plotobj1 <- plotobj1 + ggtitle("Red = Parent, Blue = Metabolite, Black = Combined")
#   plotobj1 <- plotobj1 + geom_line(aes(x = time/24/7,y = med),
#     data = summary.IPREP,
#     colour = "red",size = 1)	# Parent
#   plotobj1 <- plotobj1 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     data = summary.IPREP,
#     fill = "red",alpha = 0.3)	# Parent
#   plotobj1 <- plotobj1 + geom_line(aes(x = time/24/7,y = med),
#     data = summary.IPREM,
#     colour = "blue",size = 1)	# Metabolite
#   plotobj1 <- plotobj1 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     data = summary.IPREM,
#     fill = "blue",alpha = 0.3)	# Metabolite
#   plotobj1 <- plotobj1 + geom_line(aes(x = time/24/7,y = med),
#     data = summary.IPRE,
#     size = 1)	# Combined
#   plotobj1 <- plotobj1 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     data = summary.IPRE,
#     fill = "black",alpha = 0.3)	# Combined
#   plotobj1 <- plotobj1 + scale_y_continuous("Sunitinib Concentration (mg/L)\n")
#   plotobj1 <- plotobj1 + scale_x_continuous("\nTime (weeks)",
#     breaks = seq(from = 0,to = 12,by = 2),
#     labels = seq(from = 0,to = 12,by = 2))
#   print(plotobj1)
#
#   ggsave(plot = plotobj1,
#     filename = "sunitinib_concentrations.png",
#     dpi = 300)
#
# # Plot
#   plotobj2 <- NULL
#   plotobj2 <- ggplot(summary.AUC24)
#   plotobj2 <- plotobj2 + geom_line(aes(x = time/24/7,y = med),
#     colour = "red",size = 1)
#   plotobj2 <- plotobj2 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     fill = "red",alpha = 0.3)
#   plotobj2 <- plotobj2 + scale_y_continuous("Combined 24-hour AUC (mg*h/L)\n")
#   plotobj2 <- plotobj2 + scale_x_continuous("\nTime (weeks)",
#     breaks = seq(from = 0,to = 12,by = 2),
#     labels = seq(from = 0,to = 12,by = 2))
#   print(plotobj2)
#
#   ggsave(plot = plotobj2,
#     filename = "combined_sunitinib_auc.png",
#     dpi = 300)

# ------------------------------------------------------------------------------
# Perform PD simulations
  pd.ID.data <- pk.data[pk.data$time %in% pd.times,]
  input.pd.data <- pd.ID.data[c("SIM","ID","time","AUC24","WT","OBASE","HFSBASE",
    "FATBASE")]
  pd.ETA.matrix$SIM <- SIM.seq
  pd.ETA.matrix$ID <- ID.seq
  input.pd.data <- merge(input.pd.data,pd.ETA.matrix,by = c("SIM","ID"),all = T)
  input.pd.data$cmt <- 0
  input.pd.data$evid <- 0
  input.pd.data$RSURV <- runif(dim(input.pd.data)[1],min = 0,max = 1)
  input.pd.data$RDROP <- runif(dim(input.pd.data)[1],min = 0,max = 1)

# Simulate
  pd.data <- pd.mod %>% mrgsim(data = input.pd.data,carry.out = c("SIM")) %>%
    as.data.frame
  pd.data <- ddply(pd.data, .(SIM,ID), tumour.dropout, .progress = "text")
  # pd.data <- ddply(pd.data, .(SIM,ID), simulate.HFS.grade, .progress = "text")
  # pd.data <- ddply(pd.data, .(SIM,ID), simulate.FAT.grade, .progress = "text")
  # pd.data <- ddply(pd.data, .(SIM,ID), alive.function, .progress = "text")

# # Plot biomarkers (sVEGFR-3 and sKIT) over time
#   biomarker.data <- pd.data[pd.data$time <= 18*24*7,]	# Subset times less than 18 weeks
#   summary.IPRE_VEGFR3 <- ddply(biomarker.data, .(time),
#     function(biomarker.data) summary.function(biomarker.data$IPRE_VEGFR3))
#   summary.IPRE_SKIT <- ddply(biomarker.data, .(time),
#     function(biomarker.data) summary.function(biomarker.data$IPRE_SKIT))
#
#   plotobj3 <- NULL
#   plotobj3 <- ggplot(summary.IPRE_VEGFR3)
#   plotobj3 <- plotobj3 + geom_line(aes(x = time/24/7,y = med),
#     colour = "red",size = 1)	# sVEGFR-3
#   plotobj3 <- plotobj3 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     fill = "red",alpha = 0.3)	# sVEGFR-3
#   plotobj3 <- plotobj3 + scale_y_log10("sVEGFR-3 Concentration (pg/mL)\n",
#     breaks = c(8,10),labels = c(8,10),lim = c(8,NA))
#   plotobj3 <- plotobj3 + scale_x_continuous("\nTime (weeks)")
#   print(plotobj3)
#
#   ggsave(plot = plotobj3,
#     filename = "sVEGFR3.png",
#     dpi = 300)
#
#   plotobj4 <- NULL
#   plotobj4 <- ggplot(summary.IPRE_SKIT)
#   plotobj4 <- plotobj4 + geom_line(aes(x = time/24/7,y = med),
#     colour = "red",size = 1)	# sKIT
#   plotobj4 <- plotobj4 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     fill = "red",alpha = 0.3)	# sKIT
#   plotobj4 <- plotobj4 + scale_y_log10("sKIT Concentration (pg/mL)\n",
#     breaks = c(8,10),labels = c(8,10),lim = c(8,NA))
#   plotobj4 <- plotobj4 + scale_x_continuous("\nTime (weeks)")
#   print(plotobj4)
#
#   ggsave(plot = plotobj4,
#     filename = "sKIT.png",
#     dpi = 300)
#
# Account for drop out in tumour simulation prior to summary and plot
  tumour.data <- pd.data[pd.data$Tdrop == 0,]
  # tumour.data <- pd.data
  # tumour.nodrop.data <- tumour.nodrop.data[tumour.nodrop.data$time <= 50*24*7,]	# Subset times less than 50 weeks

# Plot tumour size over time
  TUMOUR.lo90 <- ddply(tumour.data, .(SIM,time),
    function(tumour.data) CI90lo(tumour.data$TUMOUR))
  names(TUMOUR.lo90)[3] <- c("lo90")
  TUMOUR.med <- ddply(tumour.data, .(SIM,time),
    function(tumour.data) median(tumour.data$TUMOUR))
  names(TUMOUR.med)[3] <- c("med")
  TUMOUR.hi90 <- ddply(tumour.data, .(SIM,time),
    function(tumour.data) CI90hi(tumour.data$TUMOUR))
  names(TUMOUR.hi90)[3] <- c("hi90")

  summary.TUMOUR.lo90 <- ddply(TUMOUR.lo90, .(time),
    function(TUMOUR.lo90) summary.function(TUMOUR.lo90$lo90))
  summary.TUMOUR.med <- ddply(TUMOUR.med, .(time),
    function(TUMOUR.med) summary.function(TUMOUR.med$med))
  summary.TUMOUR.hi90 <- ddply(TUMOUR.hi90, .(time),
    function(TUMOUR.hi90) summary.function(TUMOUR.hi90$hi90))

  plotobj5 <- NULL
  plotobj5 <- ggplot()
  plotobj5 <- plotobj5 + geom_line(aes(x = time/24/7,y = med),
    data = summary.TUMOUR.med,
    colour = "red",size = 1)
  plotobj5 <- plotobj5 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
    data = summary.TUMOUR.med,
    fill = "red",alpha = 0.3)
  plotobj5 <- plotobj5 + geom_line(aes(x = time/24/7,y = med),
    data = summary.TUMOUR.lo90,
    colour = "blue",size = 1)
  plotobj5 <- plotobj5 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
    data = summary.TUMOUR.lo90,
    fill = "blue",alpha = 0.3)
  plotobj5 <- plotobj5 + geom_line(aes(x = time/24/7,y = med),
    data = summary.TUMOUR.hi90,
    colour = "blue",size = 1)
  plotobj5 <- plotobj5 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
    data = summary.TUMOUR.hi90,
    fill = "blue",alpha = 0.3)
  plotobj5 <- plotobj5 + scale_y_continuous("Tumour Size (Sum of Longest Diameters, mm)\n",
    breaks = c(0,200,400,600,800,1000))
  plotobj5 <- plotobj5 + scale_x_continuous("\nTime (weeks)")
  print(plotobj5)

#   ggsave(plot = plotobj5,
#     filename = "tumour_with_dropout.png",
#     dpi = 300)
#
# # Plot absolute neutrophil count over time
#   anc.bp.data <- pd.data[pd.data$time <= 14*7*24,]	# Subset times less than 14 weeks
#   summary.ANC <- ddply(anc.bp.data, .(time),
#     function(anc.bp.data) summary.function(anc.bp.data$ANC))
#
#   plotobj6 <- NULL
#   plotobj6 <- ggplot(summary.ANC)
#   plotobj6 <- plotobj6 + geom_line(aes(x = time/24/7,y = med),
#     colour = "red",size = 1)
#   plotobj6 <- plotobj6 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     fill = "red",alpha = 0.3)
#   plotobj6 <- plotobj6 + scale_y_log10("Absolute Neutrophil Count (x10^9/L)\n",
#     breaks = c(0.1,0.5,1,2,5,10,20),labels = c(0.1,0.5,1,2,5,10,20),
#     lim = c(0.1,20))
#   plotobj6 <- plotobj6 + scale_x_continuous("\nTime (weeks)",
#     breaks = seq(from = 0,to = 14,by = 2),
#     labels = seq(from = 0,to = 14,by = 2))
#   print(plotobj6)
#
#   ggsave(plot = plotobj6,
#     filename = "absolute_neutrophil_count.png",
#     dpi = 300)
#
# # Plot diastolic blood pressure over time
#   summary.BP <- ddply(anc.bp.data, .(time),
#     function(anc.bp.data) summary.function(anc.bp.data$BP))
#
#   plotobj7 <- NULL
#   plotobj7 <- ggplot(summary.BP)
#   plotobj7 <- plotobj7 + geom_line(aes(x = time/24/7,y = med),
#     colour = "red",size = 1)
#   plotobj7 <- plotobj7 + geom_ribbon(aes(x = time/24/7,ymin = lo95,ymax = hi95),
#     fill = "red",alpha = 0.3)
#   plotobj7 <- plotobj7 + scale_y_continuous("Diastolic Blood Pressure (mm/Hg)\n",
#     breaks = c(60,80,100,120),labels = c(60,80,100,120),lim = c(50,NA))
#   plotobj7 <- plotobj7 + scale_x_continuous("\nTime (weeks)",
#     breaks = seq(from = 0,to = 14,by = 2),
#     labels = seq(from = 0,to = 14,by = 2))
#   print(plotobj7)
#
#   ggsave(plot = plotobj7,
#     filename = "diastolic_blood_pressure.png",
#     dpi = 300)
#
# # Plot proportion of individuals with different HFS grades at each time-point
#   summary.HFS <- ddply(hfs.fat.data, .(time,HFS),
#     function(hfs.fat.data) summary.count.function(hfs.fat.data$ID))
#
#   plotobj8 <- NULL
#   plotobj8 <- ggplot(summary.HFS)
#   plotobj8 <- plotobj8 + ggtitle("Hand-Foot Syndrome")
#   plotobj8 <- plotobj8 + geom_line(aes(x = time/7/24,y = pro),
#     colour = "red",size = 1)
#   plotobj8 <- plotobj8 + facet_wrap(~HFS,ncol = 2)
#   plotobj8 <- plotobj8 + scale_y_continuous("Proportion of Total Individuals\n",
#     breaks = c(0,0.2,0.4,0.6,0.8,1),
#     labels = c(0,0.2,0.4,0.6,0.8,1),
#     lim = c(0,1))
#   plotobj8 <- plotobj8 + scale_x_continuous("\nTime (weeks)")
#   print(plotobj8)
#
#   ggsave(plot = plotobj8,
#     filename = "hand_foot_syndrome.png",
#     dpi = 300)
#
# # Plot proportion of individuals with different FAT grades at each time-point
#   summary.FAT <- ddply(hfs.fat.data, .(time,FAT),
#     function(hfs.fat.data) summary.count.function(hfs.fat.data$ID))
#
#   plotobj9 <- NULL
#   plotobj9 <- ggplot(summary.FAT)
#   plotobj9 <- plotobj9 + ggtitle("Fatigue")
#   plotobj9 <- plotobj9 + geom_line(aes(x = time/7/24,y = pro),
#     colour = "red",size = 1)
#   plotobj9 <- plotobj9 + facet_wrap(~FAT,ncol = 2)
#   plotobj9 <- plotobj9 + scale_y_continuous("Proportion of Total Individuals\n",
#     breaks = c(0,0.2,0.4,0.6,0.8,1),
#     labels = c(0,0.2,0.4,0.6,0.8,1),
#     lim = c(0,1))
#   plotobj9 <- plotobj9 + scale_x_continuous("\nTime (weeks)",
#     lim = c(0,50))
#   print(plotobj9)
#
#   ggsave(plot = plotobj9,
#     filename = "fatigue.png",
#     dpi = 300)
#
# # Plot survival over time
#   surv.data <- pd.data[pd.data$TIMEW %in% surv.times,]
#   pro.alive.data <- ddply(surv.data, .(time), pro.alive.function)
#
#   plotobj10 <- NULL
#   plotobj10 <- ggplot(pro.alive.data)
#   plotobj10 <- plotobj10 + geom_step(aes(x = time/24/7,y = pro.alive*100),
#     colour = "red",size = 1)
#   plotobj10 <- plotobj10 + scale_y_continuous("Survival (%)\n",lim = c(0,100))
#   plotobj10 <- plotobj10 + scale_x_continuous("\nTime (weeks)")
#   print(plotobj10)
#
#   ggsave(plot = plotobj7,
#     filename = "overall_survival.png",
#     dpi = 300)
#
# # Kaplan Meier Plot for survival
# # All individuals have the same start time, i.e., time == 0
#   surv.data$start <- 0
#   surv.data <- ddply(surv.data, .(ID), stop.time.function)  # For each individual calculate their stop time
#   km.data <- ddply(surv.data, .(ID), headperID)
#   km.data <- km.data[c("ID","start","stop","event")]
#   S <- Surv(time = km.data$start,time2 = km.data$stop,event = km.data$event)
#   result <- survfit(formula = S ~ 1,data = km.data)
#   plot(result,
#     xscale = 24*7, # xscale labels in weeks
#     ylab = "Probability of Survival",
#     xlab = "Time (weeks)"
#   )

# ------------------------------------------------------------------------------
# Save simulation output
# Clean up pk data and save
  # output.pk.data <- pk.data[c("SIM","ID","time","amt","WT","IPREP","IPREM",
  #   "IPRE","AUC","AUC24")]
  # write.csv(output.pk.data,file = "test_sunitinib_pk_simulation.csv",
  #   quote = FALSE,row.names = FALSE)

# Clean up pd data and save
  # output.pd.data <- pd.data[c("SIM","ID","time","WT","AUC24","OBASE",
  #   "IPRE_VEGFR3","IPRE_SKIT","TUMOUR","Tdrop","ANC","BP","HFS","FAT","status")]
  # write.csv(output.pd.data,file = "test_sunitinib_pd_simulation.csv",
  #   quote = FALSE,row.names = FALSE)
